version = 0.1

[default]
[default.deploy.parameters]
stack_name = "asmbly-volunteer-dashboard-backend-dev"
resolve_s3 = true
s3_prefix = "asmbly-volunteer-dashboard-backend-dev"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppEnv=\"dev\" DomainName=\"voldash.asmbly.org\" Application=\"asmbly-volunteer-dashboard\" CertificateArn=\"arn:aws:acm:us-east-1:110104886034:certificate/68f90ebe-0412-4d64-acda-ce74442e446c\" HostedZoneId=\"Z0362110BW3J7MF2QHCA\""
image_repositories = []

[staging]
[staging.deploy.parameters]
stack_name = "asmbly-volunteer-dashboard-backend-staging"
resolve_s3 = true
s3_prefix = "asmbly-volunteer-dashboard-backend-staging"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppEnv=\"staging\" DomainName=\"staging.voldash.asmbly.org\" Application=\"asmbly-volunteer-dashboard\" CertificateArn=\"arn:aws:acm:us-east-1:110104886034:certificate/68f90ebe-0412-4d64-acda-ce74442e446c\" HostedZoneId=\"Z0362110BW3J7MF2QHCA\""

[prod]
[prod.deploy.parameters]
stack_name = "asmbly-volunteer-dashboard-backend-prod"
resolve_s3 = true
s3_prefix = "asmbly-volunteer-dashboard-backend-prod"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppEnv=\"prod\" DomainName=\"voldash.asmbly.org\" Application=\"asmbly-volunteer-dashboard\" CertificateArn=\"arn:aws:acm:us-east-1:110104886034:certificate/68f90ebe-0412-4d64-acda-ce74442e446c\" HostedZoneId=\"Z0362110BW3J7MF2QHCA\""
